### ISSUE TITLE
[BUG: DOC] Add diagram to clarify connection between XY assembly and table

### ISSUE THREAD

**Issue by Charles-W4** [MillenniumMachines/Milo-v1.5#35]
**Describe the bug**
It is unclear to me where and how many of the 90 degree corner brackets are placed. I could see 4 pictured at the ends, but apparently there are 6 per discord.

**Document Name**
Table assembly, page 96 of PDF. Not in markdown docs yet.

**Expected correction**
6 brackets and rough locations

**Screenshots**
![image](https://github.com/MillenniumMachines/Milo-v1.5/assets/38635357/d9b2b8a9-a538-4c7f-8042-44ad204409ca)

**Comment by EdwardChamberlain** [comment]
This image added to the online manual should clarify this! 
<img width="747" alt="image" src="https://github.com/MillenniumMachines/Milo-v1.5/assets/7659338/b0a490a1-55a0-40c4-a7c6-db0b1364e24f">
