### ISSUE TITLE
[BUG: DOC] Add a clear view of jumper settings(red jumpers on image) on the Fly CDY V3

### ISSUE THREAD

**Issue by barecool** [MillenniumMachines/Milo-v1.5#38]
**Describe the bug**
Add a clear view of jumper settings(red jumpers on image) on the Fly CDY V3 

- TMC2209 Driver Jumper for UART 
- CNC/laser jumper
- Z axis jumper

**Document Name**
Wiring Diagram

**Expected correction**
add image similar to the one attached below with the jumpers highlighted 
![FLY_CDY_V3_CAD_with_board_jumpers](https://github.com/MillenniumMachines/Milo-v1.5/assets/2767896/20740351-1074-4765-b0d7-e990f693a294)

**Screenshots**
see above

**Comment by EdwardChamberlain** [comment]
Are these jumpers in the image you have shared in the correct place?
