### ISSUE TITLE
Add link to web version of documentation to the repo description

### ISSUE THREAD

**Issue by pOmelchenko** [MillenniumMachines/Milo-v1.5#39]
Add link to web version of documentation to the repo description

**Comment by EdwardChamberlain** [comment]
A link to the docs is available at the bottom of the main readme page. I have moved this to the top. The description doesnt support markdown so the link looks somewhat confusing.

**Comment by pOmelchenko** [comment]
Oh. No :) I told about link in repo description, to web page https://millenniummachines.github.io/Milo-v1.5/

like this

![IMG_5789](https://github.com/MillenniumMachines/Milo-v1.5/assets/3578284/c567219c-6a7a-45f2-9ead-82440d226215)

look at Screenshot between description and license
