### ISSUE TITLE
[BUG:DOC] Add spindle earthing to Electronics Manual

### ISSUE THREAD

**Issue by benagricola** [MillenniumMachines/Milo-v1.5#41]
See print nc wiki for info 

https://discordapp.com/channels/810620766756012072/1158419436345249822/1197616574790635551

**Comment by EdwardChamberlain** [comment]
We currently have a note in the docs about this

https://github.com/MillenniumMachines/Milo-v1.5/blob/8b68b9656a596b9a22c6efe804fb264637a555b9/docs/electronics_manual/chapters/assemble_electronics.md?plain=1#L116

But could do with a dedicated image for this.

**Comment by EdwardChamberlain** [comment]
There is also a link to the print NC wiki - I think referring to that is as good as copying the info ourselves.
